# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syQGorHQUqlZyqrCq0pPGtsC5jL5Mon1
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Load the dataset and display the first 10 rows
df = pd.read_csv('AI_in_Student_Life_India.csv')
df.head(10)

# 2. Check the shape of the dataset
df.shape

# 3. Display summary information
df.info()

# 4. Generate descriptive statistics for 'Daily_Usage_Time'
df['Daily_Usage_Time'].describe()

# 5. Check for missing values
df.isnull().sum()

# 7. Total number of students per Stream
df['Stream'].value_counts()

# 6. Identify unique values in specific columns
df['State'].unique()
df['Main_AI_Tool'].unique()
df
df

#7. Total number of students per State
df['State'].value_counts()
df

# 8. Filter students who use 'ChatGPT'
chatgpt = df[df['Main_AI_Tool'] == 'ChatGPT']
chatgpt

# 9. Find average Daily_Usage_Time for 'Engineering' stream
avg_time = df[df['Stream'] == 'Engineering']['Daily_Usage_Time'].mean()
avg_time

# 10. Create a new column: Daily_Usage_Hours
df['Daily_Usage_Hours'] = df['Daily_Usage_Time']
df[['Daily_Usage_Time', 'Daily_Usage_Hours']].head()

# 12. Find top 5 states with highest average AI usage time
state = df.groupby('State')['Daily_Usage_Time'].mean().sort_values(ascending=False).head(5)
state

# Analyze the relationship between Daily_Usage_Time and Impact_on_Grades using a Scatter Plot.
sns.scatterplot(data=df)
plt.title('Daily Usage Time and  impactGrades')
plt.xlabel('Daily Use Time')
plt.ylabel('Impact Grades')

#"Show the total number of students in each stream using a plot."
stream = df['Stream'].value_counts()
stream.plot(color='skyblue')
plt.title('Number of students stream')
plt.xlabel('stream')
plt.ylabel('Count of Students')
plt.xticks(rotation=90)

# Show the distribution of main AI tools using a pie chart
tool = df['Main_AI_Tool'].value_counts()
plt.pie(tool, labels=tool)
plt.title('Main AI Tools')

# Create a histogram to show the distribution of daily usage time.
plt.hist(df['Daily_Usage_Time'], color='orange')
plt.title('Daily Use Time')
plt.xlabel(' Minutes')
plt.ylabel('Frequency')

# Show the daily usage time of students using a scatter plot.
plt.scatter(df.index, df['Daily_Usage_Time'], color='blue', marker='o')

plt.title('daily time')
plt.xlabel('Student Index')
plt.ylabel('Time ')
plt.show()

#Create a bar chart to show the number of students in each stream.
stream = df['Stream'].value_counts()

plt.bar(stream, stream.values, color='red')

plt.title('Number of Students  Stream')
plt.xlabel('Stream')
plt.ylabel('Count')